add the stop-and make post-stop-frames
DiamondLightSource/i22-bluesky pull request #76
Opened 2024-06-28 12:30 UTC by stan-dot

2024-06-28 13:46 UTC, DiamondJoseph requested changes
Please also link the linked issue in the body of the PR with "Closes <number>" and add details to that PR to the effect of what is in this PR.

2024-06-28 13:46 UTC, DiamondJoseph commented on tests/plans/test_stopflow.py
Can I get SEQ_TABLE_TEST_CASES with

```python
    (
        stopflow_seq_table(
            pre_stop_frames=1,
            post_stop_frames=0,
            exposure=0.05,
            shutter_time=4e-3,
            deadtime=2.28e-3,
            period=0.0,
        ),
...
   (
        stopflow_seq_table(
            pre_stop_frames=0,
            post_stop_frames=1,
            exposure=0.05,
            shutter_time=4e-3,
            deadtime=2.28e-3,
            period=0.0,
        ),
...
   (
        stopflow_seq_table(
            pre_stop_frames=1,
            post_stop_frames=1,
            exposure=0.05,
            shutter_time=4e-3,
            deadtime=2.28e-3,
            period=0.0,
        ),
...
   (
        stopflow_seq_table(
            pre_stop_frames=0,
            post_stop_frames=0,
            exposure=0.05,
            shutter_time=4e-3,
            deadtime=2.28e-3,
            period=0.0,
        ),

...


   (
        stopflow_seq_table(
            pre_stop_frames=200,
            post_stop_frames=0,
            exposure=0.05,
            shutter_time=4e-3,
            deadtime=2.28e-3,
            period=0.0,
        ),
```


Since we've proven that post_stop_frames 0, 1, >1 are all individual cases, and pre_stop_frames 0, >0 are different cases.

2024-06-28 14:01 UTC, stan-dot commented on tests/plans/test_stopflow.py
outlined with forced fail as AssertionError

2024-07-08 09:59 UTC, callumforrester approved these changes

2024-07-08 17:08 UTC, stan-dot commented on tests/plans/test_stopflow.py
solved

2024-07-10 13:39 UTC, DiamondJoseph approved these changes

2024-07-11 13:56 UTC, merged