87 small test plan for the pressure cell alone
DiamondLightSource/i22-bluesky pull request #93
Opened 2024-08-05 13:16 UTC by stan-dot

2024-08-05 13:18 UTC, DiamondJoseph requested changes

2024-08-05 13:18 UTC, DiamondJoseph commented on src/i22_bluesky/plans/test_pressure_cell.py
> +DEFAULT_PRESSURE_CELL = PressureCell("DEFAULT_PRESSURE_CELL")
inject
```suggestion
DEFAULT_PRESSURE_CELL = inject("DEFAULT_PRESSURE_CELL")
```

2024-08-09 08:38 UTC, callumforrester commented on src/i22_bluesky/plans/test_pressure_cell.py
> +DEFAULT_PRESSURE_CELL = inject("DEFAULT_PRESSURE_CELL")
Blueapi will not automatically inject this, that only works for function parameters

2024-08-09 08:44 UTC, DiamondJoseph commented on src/i22_bluesky/plans/test_pressure_cell.py
> +DEFAULT_PRESSURE_CELL = inject("DEFAULT_PRESSURE_CELL")
You're mistaken, this works on other plans in this repository

https://github.com/DiamondLightSource/i22-bluesky/blob/2583813a30a2f96615811ccb059e5eb7ab62125b/src/i22_bluesky/plans/stopflow.py#L59

2024-08-09 10:27 UTC, callumforrester commented on src/i22_bluesky/plans/test_pressure_cell.py
> +DEFAULT_PRESSURE_CELL = inject("DEFAULT_PRESSURE_CELL")
Ah yes, it works because the constant is include in the function signature, my bad

2024-08-16 09:42 UTC, stan-dot commented on src/i22_bluesky/plans/test_pressure_cell.py
> +DEFAULT_PRESSURE_CELL = inject("DEFAULT_PRESSURE_CELL")
@callumforrester  should this thread be resolved?

2024-08-16 10:01 UTC, DiamondJoseph commented on src/i22_bluesky/plans/test_pressure_cell.py
> +DEFAULT_PRESSURE_CELL = inject("DEFAULT_PRESSURE_CELL")
it should be `inject("high_pressure_xray_cell")` but otherwise can be resolved

cite; https://github.com/DiamondLightSource/dodal/blob/36c2344b0305e8a31d22f68ebfb5be2448b1e0d9/src/dodal/beamlines/p38.py#L329

2024-08-16 12:33 UTC, stan-dot commented on src/i22_bluesky/plans/test_pressure_cell.py
> +DEFAULT_PRESSURE_CELL = inject("DEFAULT_PRESSURE_CELL")
ok

2024-08-16 12:40 UTC, stan-dot commented
@DiamondJoseph this is problematic without a scratch directory. the CI is failing. should I hard code a git commit sha for the pressure cell commit?

the parallel development of plans and devices is a bit of a pain point

2024-08-16 13:02 UTC, stan-dot commented
that is the relevant PR https://github.com/DiamondLightSource/dodal/pull/673

2024-11-14 10:58 UTC, merged